//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delta_Impuls.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<lj> lj { get; set; }
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<ls> ls { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
