//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delta_Impuls.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class member
    {

        public int ID { get; set; }

        [Required, DisplayName("Bondsnr.")]
        public int bondsnr { get; set; }

        [Required, DisplayName("CG")]
        public bool cg { get; set; }

        [Required, DisplayName("Para TT")]
        public bool para_tt { get; set; }

        [Required, DisplayName("Geb. Datum")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime birthdate { get; set; }

        [Required, DisplayName("Geslacht")]
        public bool gender { get; set; }

        [Required, DisplayName("Voornaam")]
        [RegularExpression(@"^([a-zA-Z0-9 .&'-]+)$", ErrorMessage = "Probeer voornaam opnieuw.")]
        [StringLength(40, ErrorMessage = "Naam kan niet langer zijn dan 40 tekens.")]
        public string firstname { get; set; }

        [DisplayName("Tussenvoegsel")]
        public string insertion { get; set; }

        [Required, DisplayName("Achternaam")]
        [RegularExpression(@"^([a-zA-Z0-9 .&'-]+)$", ErrorMessage = "Probeer achternaam opnieuw.")]
        [StringLength(45, ErrorMessage = "Achternaam kan niet langer zijn dan 45 tekens.")]
        public string lastname { get; set; }

        [Required, DisplayName("Adres")]
        public string address { get; set; }

        [Required, DisplayName("Huisnummer")]
        public string housenumber { get; set; }

        [DisplayName("Huis. toev.")]
        public string suffix { get; set; }

        [Required, DisplayName("Postcode")]
        public string zipcode { get; set; }

        [Required, DisplayName("Woonplaats")]
        public string city { get; set; }

        [DisplayName("Telefoon")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Niet een geldig telefoonnummer")]
        [StringLength(20, MinimumLength = 8)]
        public string phonenumber { get; set; }

        [DisplayName("Mobiel")]
        public string mobilenumber { get; set; }

        [Required, DisplayName("E-mail")]
        [EmailAddress]
        [StringLength(45, ErrorMessage = "E-mail kan niet langer zijn dan 45 tekens.")]
        public string e_mail { get; set; }

        [Required, DisplayName("Locatie")]
        public int location_ID { get; set; }

        [DisplayName("Categorie")]
        public int category_ID { get; set; }

        [Required, DisplayName("LS")]
        public int ls_ID { get; set; }

        [Required, DisplayName("LJ")]
        public int lj_ID { get; set; }

        [Required, DisplayName("Lid sinds")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime membersince { get; set; }


        public virtual category category { get; set; }
        public virtual lj lj { get; set; }
        public virtual location location { get; set; }
        public virtual ls ls { get; set; }
    }
}


