//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delta_Impuls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int ID { get; set; }
        public int bondsnr { get; set; }
        public bool cg { get; set; }
        public bool para_tt { get; set; }
        public System.DateTime birthdate { get; set; }
        public bool gender { get; set; }
        public string firstname { get; set; }
        public string insertion { get; set; }
        public string lastname { get; set; }
        public string address { get; set; }
        public string zipcode { get; set; }
        public string city { get; set; }
        public string phonenumber { get; set; }
        public string mobilenumber { get; set; }
        public string e_mail { get; set; }
        public int location_ID { get; set; }
        public int category_ID { get; set; }
        public int ls_ID { get; set; }
        public int lj_ID { get; set; }
        public System.DateTime membersince { get; set; }
        public string housenumber { get; set; }
        public string suffix { get; set; }
    
        public virtual category category { get; set; }
        public virtual lj lj { get; set; }
        public virtual location location { get; set; }
        public virtual ls ls { get; set; }
    }
}
